- name: Install depends packages
  dnf:
    name: [ "dnf-plugins-core", "curl" ]
    state: present
  become: yes

- name: Add docker repo to fedora
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"
  become: yes

- name: Install docker and engine components
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      # حذف شد: docker-compose-plugin را از اینجا برداشتم
    state: present
  become: yes

# نصب دستی آخرین نسخه Docker Compose برای رفع خطای ورژن
- name: Install latest Docker Compose Plugin
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64
    dest: /usr/libexec/docker/cli-plugins/docker-compose
    mode: "0755"
  become: yes

- name: Start and Active docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: add docker to Sudo group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
  notify: restart docker socket