http:
  serversTransports:
    
    api-transport:
      forwardingTimeouts:
        dialTimeout: 5s
        responseHeaderTimeout: 5s
        
    web-transport:
      forwardingTimeouts:
        dialTimeout: 10s
        responseHeaderTimeout: 10s